mutation UpdateAdminUser($firstName: String!, $lastName: String!) {
    updateAdminUser(input: { userInput: { firstName: $firstName, lastName: $lastName } }) {
        errors
        user {
            corporationId
            email
            firstName
            id
            lastName
        }
    }
}


query UserAdmin {
    userAdmin {
        corporationId
        email
        firstName
        id
        lastName
    }
}
