
mutation SignIn ($email: String!, $pass: String!)
{
    signIn(input: { email: $email, password: $pass }) {
        errors
        user {
            email
            id
            firstName
        }
        token
    }
}

mutation SignUp($user: UserInput!, $password: String!) {
  signUp(input: {user: $user, password: $password}) {
    errors
    token
    user {
      corporationId
      email
      firstName
      id
      lastName
    }
  }
}

mutation UpdateAdminUser($firstName: String!, $lastName: String!) {
    updateAdminUser(input: { userInput: { firstName: $firstName, lastName: $lastName } }) {
        errors
        user {
            corporationId
            email
            firstName
            id
            lastName
        }
    }
}

