query Subsidiaries
{
    subsidiaries {
        address
        email
        id
        name
        phone
        subsidiaryInitials
    }
}

query UserAdmin {
    userAdmin {
        corporationId
        email
        firstName
        id
        lastName
    }
}
