mutation CreateTechnician($firstName: String!, $lastName: String!, $phoneNumber1: String! $email: String!, $subsidiaryId: String!) {
    createTechnician(
        input: {
            technicianInput: {
              firstName: $firstName
              lastName: $lastName
              phoneNumber1: $phoneNumber1
              email: $email
              subsidiaryId: $subsidiaryId
            }
        }
    ) {
        errors
        technician {
            corporationId
            email
            firstName
            id
            lastName
        }
    }
}

query Technicians($subsidiaryId: ID!) {
    technicians(subsidiaryId: $subsidiaryId) {
        corporationId
        email
        phoneNumber1
        firstName
        id
        lastName
    }
}

query GetTechnician($technicianId: ID!) {
    getTechnician(technicianId: $technicianId) {
        id
        firstName
        lastName
        phoneNumber1
        email
        subsidiary
        subsidiaryId
    }
}

mutation UpdateTechnician($id: ID!, $firstName: String!, $lastName: String!, $phoneNumber1: String!, $email: String!, $subsidiaryId: String!) {
    updateTechnician(
        input: {
            technicianInput: {
              id: $id
              firstName: $firstName
              lastName: $lastName
              phoneNumber1: $phoneNumber1
              email: $email
              subsidiaryId: $subsidiaryId
              }
        }
    ) {
        errors
        technician {
            corporationId
            email
            firstName
            id
            lastName
        }
    }
}